# Generated by Django 2.2 on 2019-04-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('ORG', 'Organization'), ('PER', 'Person')], default='ORG', max_length=50)),
                ('actor_name', models.CharField(max_length=200)),
            ],
        ),
    ]
