# Generated by Django 2.2 on 2019-04-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=300)),
                ('actors', models.ManyToManyField(to='datacenter.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='ActorConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actors', models.ManyToManyField(to='datacenter.Actor')),
                ('articles', models.ManyToManyField(to='datacenter.Article')),
            ],
        ),
    ]
