# Generated by Django 2.2 on 2019-04-26 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_actorconnection_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActorConnection',
        ),
    ]
